const task = (id, role, phase, title, output, accept, depends = [], extra = {}) =>
  ({ id, role, phase, title, output, accept, depends, ...extra });

export const plan = {
  version: 1,
  date: '1 Ekim 2026',
  roles: [
    { id: 'sen', name: 'İsmail Karaca', description: 'Kapsamı ve erişimi belirle, hesap bağlantını yap, ürün sonucunu kabul et.' },
    { id: 'cengiz', name: 'Hüseyin Cengiz', description: 'Sunucuyu, güvenliği, CI/CD’yi ve geri almayı kur.' },
    { id: 'asistan', name: 'Asistan Hüseyin', description: 'GoDaddy ve yetkili DNS işlemlerini verilen değerlerle uygula.' },
    { id: 'ekip', name: 'İsmail Karaca + Codex + Claude Code', description: 'Geliştirme ve repo sorumlusu İsmail Karaca. Codex ve Claude Code ile vibecoding yap; Colima’da doğrula, Docker paketini ve public GitHub repolarını hazırla, Hüseyin Cengiz’e devret.' },
  ],
  phases: [
    { id: 0, title: 'Kararları tamamla', subtitle: 'Kapsam · erişim · teslim türü', exit: 'Adres, erişim ve ürün kararlarını kaydet.' },
    { id: 1, title: 'Kaynağı, kurulum paketini ve CI’ı hazırla', subtitle: 'Vibecoding · Colima · public repo · linux/amd64', exit: 'Tek komut kurulum paketini Hüseyin Cengiz’e devret; CI’da doğrulanmış artefakt üret.' },
    { id: 2, title: 'Servisleri erişilebilir yap', subtitle: 'Sunucu · DNS · TLS', exit: 'Onaylanan erişimi aç; diğer erişimi reddet.' },
    { id: 3, title: 'Bir gerçek işi tamamla', subtitle: 'Claude iOS · MCP · oturum', exit: 'Telefondan başlayan işin doğru sonuç URL’sini al.' },
    { id: 4, title: 'Beta → RC → Pen yayınla', subtitle: 'Onay · aynı artefakt · tek yayın', exit: 'Tek component’i sürüm eşleşmesiyle Pen’de göster.' },
    { id: 5, title: 'İşletimi teslim al', subtitle: 'Geri alma · restore · gerçek cihaz', exit: 'Kabul kanıtları ve işletim devir kaydını tamamla.' },
  ],
  options: [
    { id: 'form', title: 'Webform ekle', note: 'enter.atonota.net/1 için ek iş kolunu aç.' },
    { id: 'blenderCloud', title: 'Blender’a buluttan komut ekle', note: 'Ayrı erişim onayı ve izolasyon testini aç.' },
    { id: 'separateHost', title: 'Alt yol çalışmazsa ayrı host kullan', note: 'Yeni adres onayını ve yönlendirme işlerini aç.' },
    { id: 'notifications', title: 'Bitiş bildirimi ekle', note: 'Kanal seçimi ve teslim testini aç.' },
  ],
  projects: [
    { name: 'Holding', address: 'atonota.com', action: 'Şirket → girişim envanterini ve kapsayıcı site içeriğini hazırla.', repo: 'atonota-holding-web', owner: 'sen', task: 'U01' },
    { name: 'Workbench', address: 'wb.atonota.net', action: 'Statik başlatıcıyı ayrı proje olarak yayınla; bağlantıları yeni sekmede aç.', repo: 'atonota-workbench', owner: 'ekip', task: 'E03' },
    { name: 'Pen', address: 'pen.atonota.net', action: 'Mevcut Astro arayüzünü, minimal FastAPI/PostgreSQL temelini ve Storybook’u koru.', repo: 'atonota-ui', owner: 'ekip', task: 'E02' },
    { name: 'Open Design', address: 'wb.atonota.net/od', action: 'Sürümü sabitle; ajan/BYOK ve MCP adaptörünü ayrıca doğrula.', repo: 'Upstream + Workbench altyapısı', owner: 'cengiz', task: 'H05' },
    { name: 'Penpot', address: 'wb.atonota.net/pp', action: 'Public URI, kalıcı veri, giriş/e-posta ve aktif MCP oturumunu doğrula.', repo: 'Upstream + Workbench altyapısı', owner: 'cengiz', task: 'H05' },
    { name: 'Blender', address: 'wb.atonota.net/b3d', action: 'GUI/WebSocket/Python soketini özel tut; aynı oturumu kullan.', repo: 'b3d-infra', owner: 'cengiz', task: 'H06' },
    { name: 'Storybook beta / RC', address: 'wb.atonota.net/sbbeta · /sbrc', action: 'Tek kaynak depodan iki ortam üret; yalnız onaylı RC’yi Pen’e bağla.', repo: 'atonota-ui', owner: 'ekip', task: 'E10' },
    { name: 'Affinity', address: 'wb.atonota.net/ad', action: 'Yerel bağlantı veya uzak Windows/Mac oturumu seç; Linux web uygulaması varsayma.', repo: 'Workbench bağlantı kaydı', owner: 'sen', task: 'U05' },
    { name: 'MCP geçidi', address: 'mcp.atonota.net/mcp — önerilen', action: 'HTTPS/OAuth girişini ve dar yetkili araçları geliştir; ham SSH/Docker açma.', repo: 'atonota-workbench', owner: 'ekip', task: 'E05' },
  ],
  tasks: [
    task('U01', 'sen', 0, 'Holding, şirket ve girişim listesini ver', 'Şirket/girişim adı, sahibi, domain ve mevcut repo envanteri.', 'Bilinmeyen kayıtları açıkça işaretle; sahipleri teyit et.'),
    task('U02', 'sen', 0, 'Public repo düzenini ve açık kaynak lisansını onayla', 'Holding, Workbench, Pen ve Blender için repo/lisans kararı.', 'Lisansı açıkça seç; beta ve RC için ayrı kaynak repo açma.', ['U01']),
    task('U03', 'sen', 0, 'Servis erişim sınırlarını onayla', 'Pen public; iç uygulamalar özel; bulut MCP geçidi sınırlı erişim tablosu.', 'Blender GUI/soketini public açma; onaylı cihaz/kullanıcı listesini ver.', ['H01']),
    task('U04', 'sen', 0, 'İlk işin hedefini ve çıktısını seç', 'Bir proje/oturum, bir tasarım işi ve sonuç türü: prototip / Storybook / çalışan site.', 'Yayın ve moderasyon kapısını, model/hesap bütçesini yaz; parolayı yazma.'),
    task('U05', 'sen', 0, 'Affinity erişim yöntemini seç', 'Yerel uygulama bağlantısı veya uzak Windows/Mac oturumu.', 'Workbench bağlantısının açacağı hedefi belirle.'),
    task('H01', 'cengiz', 0, 'Hetzner ve ağ envanterini çıkar', 'OS, CPU mimarisi, RAM/disk/GPU; çalışan servis/port, erişim ve kapasite kaydı.', 'Blender/render ile CI yükünü ayrı ölç; IP/secretları public plana koyma.'),
    task('A01', 'asistan', 0, 'Domain ve DNS yetkisini doğrula', 'atonota.com/.net yenileme ve nameserver/yetkili DNS sağlayıcısı kaydı.', 'GoDaddy yalnız registrar ise DNS’in gerçek sağlayıcısını belirle; kayıt değiştirme.'),
    task('E01', 'ekip', 1, 'Vibecoding kaynaklarını public GitHub repolarına aktar', 'İsmail Karaca’nın Codex ve Claude Code ile geliştirdiği kaynaklar; Holding, Workbench, Pen ve b3d repo içerikleri.', 'Geliştirme, commit ve push sorumlusu İsmail Karaca; upstream yazarlığını koru, secret/veri koyma; zip’i kaynak doğruluğu sayma.', ['U02']),
    task('E02', 'ekip', 1, 'Pen frontend ve Storybook kabulünü tamamla', 'Listing/single page, editör, dark/light/a11y, giriş yeteneği filtreleri ve test kaydı.', '320 px → masaüstü; mouse/touch/klavye; kod + preview aynı anda; düzenleme açıkça görünür.', ['E01']),
    task('E03', 'ekip', 1, 'Holding sitesi ve Workbench başlatıcısını geliştir', 'İki bağımsız statik site; logo + metin bağlantıları; şirket/girişim ilişkileri.', 'Telefon/klavye ile gezin; yeni sekme bağlantılarında güvenli rel kullan.', ['E01', 'U05']),
    task('E13', 'ekip', 1, 'Tek komut kurulum ve linux/amd64 paketini hazırla', 'Kurulabilir ürün/servis repolarında Dockerfile, Compose, güvenli .env.example, bağımlılık kilitleri, healthcheck, kurulum scripti/komutu, README ve CI kontrolleri; statik sitelerde deploy çıktısı.', 'İsmail Karaca Colima’da geliştirip GitHub’a aktarır. Temiz linux/amd64 ortamında tek komut build/start ve healthcheck kanıtını, sürüm/commit/checksum veya image digestini Hüseyin Cengiz’e verir. Mac sonucu Hetzner AMD EPYC kabulü değildir; secret repoya girmez.', ['E02', 'E03']),
    task('H02', 'cengiz', 1, 'Teslim paketinin CI ve artefakt güvenliğini kur', 'İsmail Karaca’nın repo/paketi → PR kontrolü → main beta → kontrollü RC; sabit araç/image digestleri ve linux/amd64 smoke testi.', 'Tek komut kurulum sözleşmesini doğrula; güvenilmeyen kodu üretim secretlı runner’da çalıştırma; Git yazar korumasını bulutta ayrıca uygula.', ['E01', 'E13', 'U03']),
    task('E04', 'ekip', 1, 'Component yayın sözleşmesini oluştur', 'ID, sürüm, commit, checksum, framework/story, tema ve cihaz/girdi kanıtı manifesti.', 'Storybook çıktısı ile kaynak paketini aynı sürüme bağla; DOM’dan kod kazıma.', ['E01']),
    task('H03', 'cengiz', 2, 'Sunucu güvenliğini ve kalıcı depoyu hazırla', 'Docker Engine/Compose, secret yönetimi, TLS proxy, health/log, kota, off-host yedek.', 'DB/Docker yönetimini public açma; minimum yetki ve özel ağ sınırını doğrula.', ['U03']),
    task('H04', 'cengiz', 2, 'Alt yolları dene ve DNS değişiklik föyünü ver', 'wb/pen/mcp için tam kayıt türü, adı, değeri, TTL, eski kayıt ve geri alma adımı.', 'Asset, OAuth callback ve WebSocket’i /od /pp /b3d /sbbeta /sbrc altında dene.', ['H03', 'A01']),
    task('A02', 'asistan', 2, 'Onaylanan DNS kayıtlarını uygula', 'Yalnız Hüseyin Cengiz’in föyündeki kayıtlar; değişiklik saati ve kontrol çıktısı.', 'Hedefler verilmeden tahmin etme; MX/TXT/NS kayıtlarını silme; IPv6 teyitsiz AAAA ekleme.', ['H04']),
    task('H05', 'cengiz', 2, 'DNS/TLS’yi doğrula ve teslim paketlerini Hetzner’de kur', 'İsmail Karaca’nın doğrulanmış repo/paketleri; Open Design, Penpot, beta/RC; holding/WB/Pen’in bağımsız deploy hedefleri.', 'AMD EPYC linux/amd64 üzerinde tek komut kurulum ve healthcheck’i doğrula; Docker Engine kullan. Sabit sürüm, kalıcı veri, yetkisiz erişim reddi, ortak origin ve çerez testleri.', ['A02', 'H02'], { optionalDepends: ['S03'] }),
    task('H06', 'cengiz', 2, 'Blender’ı özel stüdyo olarak kur', 'Selkies /b3d, onaylı Tailscale cihazları, aynı Blender sürecine kontrollü MCP tüneli.', 'Public GUI/WS/Python reddi; restart sonrası dosya/eklenti; socket/volume/privileged sınırı.', ['H05']),
    task('E05', 'ekip', 3, 'Uzak MCP geçidini ve sınırlı araçları geliştir', 'apps.list, jobs.start/status/result; HTTPS/OAuth; proje/oturum/eylem yetkisi.', 'Anthropic bulutundan bağlantı, kullanıcı ayrımı ve izin iptalini test et; SSH şifresi isteme.', ['H05', 'U04']),
    task('E06', 'ekip', 3, 'Kalıcı iş yürütücüsünü ve adaptörleri geliştir', 'İş kimliği, durum/sonuç, idempotency, iptal/timeout/audit; Penpot ve Open Design adaptörü.', 'İzole build/kod; üretim DB/secret erişimi yok; Pen’in geniş backend şemasını sonraya bırak.', ['E05']),
    task('H07', 'cengiz', 3, 'Penpot aktif oturumunu ve worker kurtarmasını kur', 'Doğru dosya/sayfaya bağlı tarayıcı/eklenti; yeniden bağlanma ve seri yazma.', 'Telefon kapalı, worker restart ve oturum kopmasında yanlış proje/çift iş oluşmasın.', ['E06']),
    task('U06', 'sen', 3, 'Claude hesabına MCP bağlantısını ekle', 'Önce web/Desktop’ta connector; aynı hesapla iOS’ta sınırlı araç izni.', 'Gerçek hesabında giriş ve izinleri doğrula; sunucu parolası/token paylaşma.', ['H07']),
    task('E07', 'ekip', 3, 'Telefondan bir gerçek işi uçtan uca test et', 'Seçilen tasarım işi, doğru uygulama oturumu ve doğru türde sonuç URL’si.', 'İzin iptali, telefon kapanması, timeout ve yeniden denemede tek iş kaydı.', ['U06']),
    task('E08', 'ekip', 3, 'Blender’da aynı oturumda kaydet/gör denemesi yap', 'Özel ağdan MCP nesne oluşturma, dosya kaydı ve GUI’de aynı sahne.', 'Bağlantı/restart ve orta sahne yükünü test et; ham Python’u bulut aracı yapma.', ['H06']),
    task('E09', 'ekip', 4, 'RC → MCP → Pen yayın köprüsünü geliştir', 'Başarılı RC deploy’dan kalıcı iş; dar yetkili sync_release; doğrulanmış artefakt.', 'İmza/checksum, kaynak allowlist’i, eski/duplicate olay ve yayın döngüsü koruması.', ['E04', 'E06']),
    task('E10', 'ekip', 4, 'Tek component’i beta’da doğrula', 'Storybook sitesi + kaynak paketi + ortak manifest; browser/a11y/build kanıtı.', 'Aynı ID/sürüm/commit; framework adaptörü; uyumluluk filtrelerine gerçek kanıt.', ['H02', 'E02', 'E09']),
    task('U07', 'sen', 4, 'Beta sonucu ve RC terfisini kabul et', 'Ürün kabul kaydı; yayın/moderasyon kararı.', 'Seçtiğin çıktı çalışsın; UX/DX kabulü ve eksikler kaydedilsin.', ['E10', 'E07']),
    task('H08', 'cengiz', 4, 'Aynı artefaktı RC’ye terfi ettir', 'Yeni build yapmadan test edilmiş artefaktı RC’ye taşı; deploy smoke testi.', 'Ürün kabulü + teknik kontrol; başarısız RC, Pen’i değiştirmesin.', ['U07']),
    task('E11', 'ekip', 4, 'RC yayınıyla Pen güncellemesini doğrula', 'MCP köprüsüyle otomatik yayın ve sonuç URL’si; sürüm/commit/checksum eşleşmesi.', 'Aynı olayı tekrar gönder; tek yayın ve gerilemeyen sürüm doğrula.', ['H08']),
    task('H09', 'cengiz', 5, 'Rollback, restore ve arıza provasını tamamla', 'Son iyi artefakta dönüş, off-host yedekten restore, izleme/uyarı ve devir runbook’u.', 'Disk/kota, TLS/token süresi ve kısmi yayını dene; kanıtı secret içermeden kaydet.', ['E11', 'E03', 'E08']),
    task('E12', 'ekip', 5, 'Gerçek cihaz ve erişim kabul kanıtlarını topla', 'iOS/Android/macOS; dokunma/klavye/fare; kopma, gecikme, dosya ve odak testleri.', 'pass / fail / not_run ayrı; emülasyonu gerçek cihaz testi sayma.', ['H09']),
    task('U08', 'sen', 5, 'Sonuçları kabul et ve işletimi devral', 'Açık eksik listesi, görev sahipleri, sonuç URL’leri ve sonraki waterfall backend brief’i.', 'Başarısız kontroller kapanmadan tam teslim sayma; bakım ve yenileme sorumlularını teyit et.', ['E12'], { optionalDepends: ['F03', 'B03', 'S03', 'N03'] }),
    task('F01', 'sen', 0, 'Webform kapsamını seç', 'enter.atonota.net/1 için izinli kullanıcı, dosya limiti ve ilk eylemler.', 'Formu zorunlu kanal yapma; Claude ile aynı iş sözleşmesini kullan.', [], { when: 'form' }),
    task('F02', 'ekip', 3, 'Webform’u ortak iş sözleşmesine bağla', 'Mobil metin/dosya formu → küçük FastAPI giriş servisi → kalıcı iş → worker/MCP.', 'Kimlik doğrulama, rate limit ve yükleme sınırı; credential tarayıcıya gitmesin.', ['F01', 'E06'], { when: 'form' }),
    task('FH01', 'cengiz', 2, 'enter için tam DNS föyünü hazırla', 'Kayıt türü/adı/değeri, TTL, eski kayıt ve geri alma adımı.', 'Yalnız onaylanan form erişimini hedefle; föyü Asistan Hüseyin’e ver.', ['F01', 'H04'], { when: 'form' }),
    task('F03', 'cengiz', 5, 'Form adresini ve güvenli girişi doğrula', 'DNS sonrası TLS/erişim ve uçtan uca iş testi.', 'Özel erişim politikasını koru; iş durumunu aynı kullanıcı sorgulasın.', ['F02', 'FA01'], { when: 'form' }),
    task('FA01', 'asistan', 3, 'enter DNS kaydını föye göre uygula', 'Hüseyin Cengiz’den alınan enter kayıt türü/adı/değeri.', 'Kayıt değerlerini Cengiz’e doğrulat; uygulama yolu /1 için DNS kaydı açma.', ['FH01'], { when: 'form' }),
    task('B01', 'sen', 0, 'Blender bulut komut yetkisini ayrıca onayla', 'İzinli eylem/proje; ağ sınırı; buluta gönderilebilir veri.', 'GUI/WS/Python özel kalsın; bulut istemcisini Tailscale cihazı sayma.', ['U03'], { when: 'blenderCloud' }),
    task('B02', 'ekip', 3, 'Blender bulut adaptörünü izole et', 'Sınırlı araçlar, aynı oturum, seri yazma, iptal/yetki tekrar kontrolü.', 'Ham Python ve serbest dosya/terminal yok; izinsiz sahne erişimi reddedilsin.', ['B01', 'E08', 'E06'], { when: 'blenderCloud' }),
    task('B03', 'cengiz', 5, 'Bulut komut izolasyonunu doğrula', 'İzinli işin aynı sahnede sonucu; dış ağdan GUI/WS/socket reddi.', 'Yetki iptali, yanlış kullanıcı/proje ve eşzamanlı yazma testleri.', ['B02'], { when: 'blenderCloud' }),
    task('S01', 'sen', 2, 'Başarısız alt yol için yeni adresi onayla', 'Başarısız uygulama testi + izole host + eski URL yönlendirmesi.', 'Adres değişikliğini açıkça kabul et; sessizce subdomain değiştirme.', ['H04'], { when: 'separateHost' }),
    task('SH01', 'cengiz', 2, 'Onaylanan izole host için DNS föyünü ver', 'Yeni hostun kayıt türü/adı/değeri, TTL ve rollback kaydı.', 'Yeni hedefin erişim sınırını koru; föyü Asistan Hüseyin’e ver.', ['S01'], { when: 'separateHost' }),
    task('S02', 'asistan', 2, 'İzole host DNS kaydını föye göre uygula', 'Hüseyin Cengiz’in yeni host için hazırladığı kayıtlar.', 'Yeni adres onayı olmadan uygulama yapma; eski kayıt/rollback bilgisi korunsun.', ['SH01'], { when: 'separateHost' }),
    task('S03', 'cengiz', 2, 'Yönlendirme ve callback’leri doğrula', 'İzole host proxy/TLS; eski URL yönlendirmesi; public URI ve OAuth/WS ayarı.', 'Giriş, asset ve WebSocket yeni adreste çalışsın; eski URL çıkmaz sokak olmasın.', ['S02'], { when: 'separateHost' }),
    task('N01', 'sen', 0, 'Bildirim kanalını ve iznini seç', 'Telegram / e-posta / web push gibi bir kanal; izinli alıcı ve veri kapsamı.', 'Claude iOS’tan kendiliğinden bildirim geleceğini varsayma.', [], { when: 'notifications' }),
    task('N02', 'ekip', 3, 'Bitiş/başarısızlık bildirimini ekle', 'Kalıcı iş olayı → seçilen kanal; güvenli sonuç bağlantısı.', 'Retry çift bildirim üretmesin; token/secret veya özel dosya içeriği gönderme.', ['N01', 'E06'], { when: 'notifications' }),
    task('N03', 'sen', 5, 'Telefon kapalıyken bildirimi doğrula', 'İş bittikten sonra alınan tek bildirim ve erişilebilir sonuç URL’si.', 'Başarısız iş ve alıcı/izin iptalini de dene.', ['N02', 'E07'], { when: 'notifications' }),
  ],
};
