import { normalizeState, statusOf, dependenciesOf, isActive } from './model.mjs';

export const escapeHTML = value => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
export const statusLabels = { ready: 'Hazır', waiting: 'Ön koşul bekliyor', done: 'Tamamlandı', inactive: 'Koşul kapalı' };
const link = (href, label, className = '') => `<a class="${className}" href="${escapeHTML(href)}">${escapeHTML(label)}</a>`;
const title = (number, heading, description = '') => `<div class="section-heading"><p class="eyebrow">${escapeHTML(number)}</p><h2>${escapeHTML(heading)}</h2>${description ? `<p>${escapeHTML(description)}</p>` : ''}</div>`;

export function renderDependencyLinks(task, state, plan) {
  const dependencies = dependenciesOf(task, state, plan);
  return dependencies.length ? `Ön koşul: ${dependencies.map(id => {
    const prerequisite = plan.tasks.find(task => task.id === id);
    return `<a class="dependency-link" href="#task-${id}" aria-label="${id}: ${escapeHTML(prerequisite.title)}">${id}${state.completed.includes(id) ? ' · tamam' : ' · bekliyor'}</a>`;
  }).join(' ')}` : 'Ön koşul yok; başlayabilirsin.';
}

export function renderTask(task, state, plan) {
  const status = statusOf(task, state, plan);
  return `<li class="task" id="task-${task.id}" data-task="${task.id}" data-status="${status}" ${status === 'inactive' ? 'hidden' : ''}>
    <label class="task-check"><input type="checkbox" tabindex="0" data-complete="${task.id}" disabled ${status === 'done' ? 'checked' : ''} aria-describedby="status-${task.id} deps-${task.id}"><span class="sr-only">${task.id}: ${escapeHTML(task.title)} — tamamlandı olarak işaretle</span></label>
    <div class="task-copy"><div class="task-id">${task.id}</div><h4 class="task-title">${escapeHTML(task.title)}</h4><span class="task-status" id="status-${task.id}" data-task-status="${task.id}">${statusLabels[status]}</span>
    <details class="task-detail" id="detail-${task.id}"><summary>Çıktı ve kabul<span class="sr-only">: ${task.id}</span></summary><div class="task-meta" id="meta-${task.id}"><p><strong>Çıktı:</strong> ${escapeHTML(task.output)}</p><p><strong>Kabul:</strong> ${escapeHTML(task.accept)}</p></div></details>
    <div class="dependencies" id="deps-${task.id}" data-dependencies="${task.id}">${renderDependencyLinks(task, state, plan)}</div></div></li>`;
}

export function renderNext(plan, state, role = 'all') {
  const ready = plan.tasks.filter(task => statusOf(task, state, plan) === 'ready' && (role === 'all' || task.role === role))
    .sort((left, right) => Number(left.decision === true) - Number(right.decision === true));
  if (!ready.length) {
    const waiting = plan.tasks.filter(task => statusOf(task, state, plan) === 'waiting' && (role === 'all' || task.role === role));
    return `<p class="empty-state">${waiting.length ? 'Hazır iş yok. Bekleyen görevdeki ön koşula git.' : 'Bu kapsamda açık iş yok. Genel yoldan durumu kontrol et.'}</p>`;
  }
  return `<ol class="next-actions">${ready.slice(0, 5).map(task => {
    const owner = plan.roles.find(item => item.id === task.role);
    return `<li class="next-item"><div class="next-meta">${escapeHTML(owner.name)} <span>· ${task.id}</span></div>${link(`#task-${task.id}`, task.title)}</li>`;
  }).join('')}</ol>${ready.length > 5 ? `<p>${ready.length - 5} hazır işi daha ${link('#kisiler', 'kişisel yol haritalarında gör')}.</p>` : ''}`;
}

export function renderPage(plan, progress = null) {
  const state = normalizeState(progress, plan);
  const roleName = id => plan.roles.find(role => role.id === id).name;
  const active = plan.tasks.filter(task => isActive(task, state));
  const readyCount = active.filter(task => statusOf(task, state, plan) === 'ready').length;
  const roadmap = plan.phases.map(phase => {
    const tasks = active.filter(task => task.phase === phase.id);
    const completed = tasks.filter(task => state.completed.includes(task.id)).length;
    return `<li class="stage" data-phase="${phase.id}"><div class="stage-head"><span class="stage-number">0${phase.id + 1}</span><div class="stage-title"><h3>${escapeHTML(phase.title)}</h3><p>${escapeHTML(phase.subtitle)}</p></div><span class="stage-status" data-phase-status="${phase.id}">${completed} / ${tasks.length}</span></div><p>${escapeHTML(phase.exit)}</p><div class="owner-links">${plan.roles.filter(role => tasks.some(task => task.role === role.id)).map(role => link(`#role-${role.id}-phase-${phase.id}`, `${role.name} · ${tasks.filter(task => task.role === role.id).length} görev`, 'owner-link')).join('')}</div></li>`;
  }).join('');
  const roles = plan.roles.map(role => `<section class="role-section" id="role-${role.id}" aria-labelledby="heading-${role.id}"><div class="role-heading"><h3 id="heading-${role.id}">${escapeHTML(role.name)}</h3><span class="role-summary" data-role-status="${role.id}">${active.filter(task => task.role === role.id && state.completed.includes(task.id)).length} / ${active.filter(task => task.role === role.id).length}</span></div><p>${escapeHTML(role.description)}</p><div class="role-phases">${plan.phases.filter(phase => plan.tasks.some(task => task.role === role.id && task.phase === phase.id)).map(phase => {
    const tasks = plan.tasks.filter(task => task.role === role.id && task.phase === phase.id);
    const visible = tasks.filter(task => isActive(task, state));
    return `<details class="role-phase" id="role-${role.id}-phase-${phase.id}" data-role-phase="${role.id}:${phase.id}" ${role.id === 'sen' && phase.id === 0 ? 'open' : ''} ${visible.length === 0 ? 'hidden' : ''}><summary>0${phase.id + 1} · ${escapeHTML(phase.title)}<span data-group-status="${role.id}:${phase.id}">${visible.filter(task => state.completed.includes(task.id)).length} / ${visible.length}</span></summary><div class="phase-content"><ul class="task-list">${tasks.map(task => renderTask(task, state, plan)).join('')}</ul></div></details>`;
  }).join('')}</div></section>`).join('');
  const flow = (name, steps, dependencyMap = false) => `<figure class="flow"><figcaption>${escapeHTML(name)}</figcaption><ol class="flow-list${dependencyMap ? ' dependency-map' : ''}">${steps.map(([id, heading, note]) => {
    const task = plan.tasks.find(task => task.id === id);
    const status = statusOf(task, state, plan);
    return `<li data-flow-task="${id}" data-status="${status}"><span class="flow-step">${link(`#task-${id}`, heading)}</span><span class="flow-label">${link(`#role-${task.role}-phase-${task.phase}`, note ?? roleName(task.role), 'flow-owner-link')}</span><span class="flow-node-state" data-flow-status="${id}">${statusLabels[status]}</span>${dependencyMap ? `<div class="flow-dependencies" data-flow-dependencies="${id}">${renderDependencyLinks(task, state, plan)}</div>` : ''}</li>`;
  }).join('')}</ol></figure>`;
  const branches = `<div class="branch-diagram" aria-label="Seçilen ek iş kolları">${plan.options.map(option => `<section class="branch-node" data-branch="${option.id}" aria-labelledby="branch-heading-${option.id}" ${state.options[option.id] ? '' : 'hidden'}><h3 id="branch-heading-${option.id}">${escapeHTML(option.title)}</h3>${flow('İş kolu düğümleri; ön koşul bağlantılarını izle.', plan.tasks.filter(task => task.when === option.id).sort((left, right) => left.phase - right.phase).map(task => [task.id, task.title]), true)}</section>`).join('')}</div>`;
  return `<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><meta name="description" content="Atonota: genel ve kişisel yol haritaları, koşullu görevler, CI/CD, DNS ve MCP eylem planı."><meta name="referrer" content="strict-origin-when-cross-origin"><title>Atonota — Eylem planı</title><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css"><script type="module" src="./app.mjs"></script></head>
<body><a class="skip-link" href="#main">İçeriğe geç</a><header class="masthead"><a class="brand" href="#main">atonota <span> / eylem planı</span></a><div class="masthead-meta">${plan.date} · <a href="https://github.com/karacaismail/atonota-action-plan" target="_blank" rel="noopener noreferrer">Public repo</a></div></header>
<div class="layout"><nav class="rail" aria-label="Plan bölümleri"><details class="rail-menu" id="rail-menu"><summary>Plan ve kişiler</summary><p>Yol haritası</p><div class="rail-links">${[['#simdi','Şimdi başla'],['#genel','Genel yol'],['#akislar','İş akışları'],['#kisiler','Kişiler'],['#projeler','Projeler'],['#kararlar','Eksikler ve kararlar']].map(([href,label]) => link(href,label,'rail-link')).join('')}</div><p>Kişisel yollar</p><div class="rail-links">${plan.roles.map(role => link(`#role-${role.id}`,role.name,'rail-link')).join('')}</div></details></nav>
<main id="main"><div class="hero"><p class="eyebrow">Workbench · MCP · Pen</p><h1>Hazır işten<br>ilk sonuca.</h1><p class="lede">Akışta sıradaki adımı bul.<br>Görev sahibine geç, sonucu doğrula.</p><div class="overview-actions">${link('#simdi','Hazır işi bul','overview-action')}<a class="overview-action" href="https://karacaismail.github.io/atonota-workbench/" target="_blank" rel="noopener noreferrer">Workbench’i aç<span class="sr-only"> — yeni sekme</span></a></div><div class="known-decisions"><h2>Kayıtlı kararlar</h2><ul><li><strong>Adresler:</strong> wb.atonota.net/* iç uygulamalar; Pen ayrı: pen.atonota.net.</li><li><strong>Kaynak:</strong> varsa kendi upstream reposu; özgün kod karacaismail public reposunda.</li><li><strong>Hedef:</strong> ayrı dedicated AMD EPYC · 128 GB RAM (kullanıcı beyanı). Dört Frappe sunucusu kapsam dışı.</li></ul></div><div class="notice"><strong>Yerel takip.</strong> İşaretler bu tarayıcıdadır; gerçek kurulum, erişim onayı veya deploy değildir.</div><div class="summary" aria-label="Plan özeti"><div class="metric"><strong data-metric="done">${state.completed.length} / ${active.length}</strong><span>tamamlandı · yerel takip</span></div><div class="metric"><strong data-metric="ready">${readyCount}</strong><span>başlanabilir görev</span></div><div class="metric"><strong>${plan.phases.length}</strong><span>ilişkili aşama</span></div><div class="metric"><strong>${plan.roles.length}</strong><span>görev sahibi</span></div></div></div>
<section id="simdi">${title('01 / Sıradaki iş', 'Şimdi ne yapacağım?', 'Görev sahibini seç; ön koşulu tamamlanan işe git.')}<div class="toolbar" aria-label="Hazır işleri görev sahibine göre göster"><button type="button" data-owner-filter="all" aria-pressed="true">Herkes</button>${plan.roles.map(role=>`<button type="button" data-owner-filter="${role.id}" aria-pressed="false">${escapeHTML(role.name)}</button>`).join('')}</div><div id="next-actions">${renderNext(plan,state)}</div></section>
<section id="genel">${title('02 / Teknik yol', 'Aşamadan görev sahibine geç.', 'Kişiye dokun: ilgili aşaması açılır. Bağımsız işler paralel ilerler; sayılar yerel işaretlerini gösterir.')}<ol class="stage-list">${roadmap}</ol><div class="section-heading"><h3>Ek iş kolunu aç</h3><p>Seçilen kolun şeması ve görevleri görünür. Seçim gerçek erişim veya yayın izni değildir.</p></div><div class="branch-options">${plan.options.map(option=>`<div class="option"><label><input type="checkbox" data-option="${option.id}" disabled ${state.options[option.id] ? 'checked' : ''}><span>${escapeHTML(option.title)}</span></label><small>${escapeHTML(option.note)}</small></div>`).join('')}</div>${branches}</section>
<section id="akislar">${title('03 / İş akışı', 'Adıma dokun, görevine geç.', 'Göreve veya sahibine git. Durumlar işaretlerinle güncellenir; servis sağlığı değildir. Ek ön koşullar ilgili görevde görünür.')}${flow('Kaynak → Workbench → paket → sunucu', [['E01','Kaynağı hazırla'],['E03','Workbench’i yayınla'],['E13','Colima’da paketi doğrula'],['H02','CI’ı kur'],['H05','Hetzner’de kur']])}${flow('DNS: teknik föy → uygulama → doğrulama', [['H04','DNS föyünü hazırla'],['A02','DNS’i uygula'],['H05','DNS / TLS’yi doğrula']])}${flow('MCP hazırlığı → Claude iOS → sonuç URL’si', [['E05','MCP araçlarını hazırla'],['E06','Kalıcı işi yürüt'],['H07','Doğru oturumu bağla'],['U06','Claude iOS’u bağla',`${roleName('sen')} · Claude iOS`],['E07','İlk sonuç URL’sini al']])}${flow('Component: manifest → köprü → beta → RC → Pen', [['E04','Manifesti hazırla'],['E09','Yayın köprüsünü kur'],['E10','Beta’da test et'],['U07','Ürün kabulünü yap'],['H08','Aynı artefaktı RC’ye taşı'],['E11','Pen’de yayını doğrula']])}</section>
<section id="kisiler">${title('04 / Kişisel yollar', 'Kendi görevlerini tamamla.', 'İsmail Karaca’nın karar, geliştirme ve kabul görevleri tek yol haritasında. Codex ve Claude Code geliştirme araçlarıdır. Ön koşul bağlantısından ilgili işe geç.')}<noscript><p class="notice">Planı okuyabilir ve bağlantıları kullanabilirsin. Yerel işaretleme ve koşullu kollar için JavaScript’i etkinleştir.</p></noscript>${roles}</section>
<section id="projeler">${title('05 / Adres ve repo', 'Bilinen hedeflerle ayrı teslim et.', 'Uygulama yolları ve repo politikası kayıtlı: mevcut uygulama kendi upstream reposundan; özgün kaynak ve özel kurulum karacaismail’in public reposundan. Oluşturulacak repo adları öneridir. Yalnız eksik şirket/girişim ilişkileri ve özgün kod lisansı ayrı karar bekler.')}<div class="project-list">${plan.projects.map(project=>`<article class="project"><div><h3 class="project-name">${project.name}</h3><p class="project-address">${escapeHTML(project.address)}</p></div><div><p>${escapeHTML(project.action)}</p><p class="project-note">Repo: ${escapeHTML(project.repo)}</p>${link(`#task-${project.task}`,`${plan.roles.find(role=>role.id===project.owner).name} · ${project.task}`,'owner-link')}</div></article>`).join('')}</div><p class="notice">/od, /pp ve /b3d birer alt yoldur: DNS kaydı açma. Proxy ve uygulama base path’ini Hüseyin Cengiz doğrulasın. Çalışmazsa yeni adresi önce onayla.</p></section>
<section id="kararlar">${title('06 / Gerçek açık işler', 'Kararı teknik işten ayır.')}<ul class="next-actions"><li class="next-item"><h3>${escapeHTML(roleName('sen'))}: eksik kararları tamamla.</h3><p>Yalnız verilmemiş gerçek şirket/girişim ilişkileri ve yeni özgün kodun lisansı. Workbench hazırlığını bekletmez.</p>${link('#task-U01','Şirket envanteri','owner-link')} ${link('#task-U02','Özgün kod lisansı','owner-link')}</li><li class="next-item"><h3>${escapeHTML(roleName('cengiz'))}: uyumluluk ve işletimi kanıtla.</h3><p>Dedicated hedefin ölçümleri, kayıtlı erişim kuralları, Affinity’nin gerçek Windows/Mac oturumu ve alt yollar.</p>${link('#role-cengiz-phase-0','Teknik doğrulamaya git','owner-link')}</li><li class="next-item"><h3>${escapeHTML(roleName('asistan'))}: DNS föyünü uygula.</h3><p>Domain seçimini tekrar sorma; verilen kayıt türü, adı, değeri ve rollback kaydıyla ilerle.</p>${link('#task-A02','DNS görevine git','owner-link')}</li><li class="next-item"><h3>${escapeHTML(roleName('sen'))}: eksik köprüleri geliştir.</h3><p>Dar yetkili MCP, kalıcı iş yürütücüsü, doğru uygulama oturumu ve RC → Pen yayın köprüsü.</p>${link('#role-sen-phase-3','Geliştirme aşamasına git','owner-link')}</li></ul></section>
<footer class="footer"><div class="toolbar"><button type="button" id="export-progress" disabled>İlerlemeyi indir</button><button type="button" id="reset-progress" disabled>Yerel işaretleri sıfırla</button></div><p class="completion-feedback" id="feedback" role="status" aria-live="polite">İşaretlemek, gerçek kurulumun tamamlandığı anlamına gelmez.</p><p id="storage-note">Takip verisi bu tarayıcıya özeldir. Senkronize ekip panosu değildir.</p><p>Kaynak kontrolleri: <a href="https://docs.github.com/en/actions/reference/security/secure-use">CI güvenliği</a> · <a href="https://help.penpot.app/mcp/">Penpot MCP</a> · <a href="https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp">Uzak connector</a> · <a href="https://storybook.js.org/docs/sharing/publish-storybook">Storybook yayını</a></p></footer>
</main></div></body></html>`;
}
