import { normalizeState, statusOf, dependenciesOf } from './model.mjs';

export const escapeHTML = value => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
export const statusLabels = { ready: 'Hazır', waiting: 'Ön koşul bekliyor', done: 'Tamamlandı', inactive: 'Koşul kapalı' };
const link = (href, label, className = '') => `<a class="${className}" href="${href}">${escapeHTML(label)}</a>`;
const title = (number, heading, description = '') => `<div class="section-heading"><p class="eyebrow">${number}</p><h2>${heading}</h2>${description ? `<p>${description}</p>` : ''}</div>`;

export function renderTask(task, state, plan) {
  const status = statusOf(task, state, plan);
  const dependencies = dependenciesOf(task, state, plan);
  return `<li class="task" id="task-${task.id}" data-task="${task.id}" data-status="${status}" ${status === 'inactive' ? 'hidden' : ''}>
    <label class="task-check"><input type="checkbox" tabindex="0" data-complete="${task.id}" disabled aria-describedby="meta-${task.id}"><span class="sr-only">${task.id}: ${escapeHTML(task.title)} — tamamlandı olarak işaretle</span></label>
    <div class="task-copy"><div class="task-id">${task.id}</div><h4 class="task-title">${escapeHTML(task.title)}</h4><span class="task-status" data-task-status="${task.id}">${statusLabels[status]}</span>
    <div class="task-meta" id="meta-${task.id}"><p><strong>Çıktı:</strong> ${escapeHTML(task.output)}</p><p><strong>Kabul:</strong> ${escapeHTML(task.accept)}</p></div>
    <div class="dependencies" data-dependencies="${task.id}">${dependencies.length ? `Ön koşul: ${dependencies.map(id => link(`#task-${id}`, id, 'dependency-link')).join(' ')}` : 'Ön koşul yok; başlayabilirsin.'}</div></div></li>`;
}

export function renderNext(plan, state, role = 'all') {
  const ready = plan.tasks.filter(task => statusOf(task, state, plan) === 'ready' && (role === 'all' || task.role === role));
  if (!ready.length) {
    const waiting = plan.tasks.filter(task => statusOf(task, state, plan) === 'waiting' && (role === 'all' || task.role === role));
    return `<p class="empty-state">${waiting.length ? 'Hazır iş yok. Bekleyen görevdeki ön koşula git.' : 'Bu kapsamda açık iş yok. Genel yoldan durumu kontrol et.'}</p>`;
  }
  return `<ol class="next-actions">${ready.slice(0, 5).map(task => {
    const owner = plan.roles.find(item => item.id === task.role);
    return `<li class="next-item"><div class="next-meta">${escapeHTML(owner.name)} <span>· ${task.id}</span></div>${link(`#task-${task.id}`, task.title)}<p>${escapeHTML(task.output)}</p></li>`;
  }).join('')}</ol>${ready.length > 5 ? `<p>${ready.length - 5} hazır işi daha ${link('#kisiler', 'kişisel yol haritalarında gör')}.</p>` : ''}`;
}

export function renderPage(plan) {
  const state = normalizeState(null, plan);
  const core = plan.tasks.filter(task => !task.when);
  const readyCount = core.filter(task => statusOf(task, state, plan) === 'ready').length;
  const roadmap = plan.phases.map(phase => {
    const tasks = core.filter(task => task.phase === phase.id);
    return `<li class="stage" data-phase="${phase.id}"><div class="stage-head"><span class="stage-number">0${phase.id + 1}</span><div class="stage-title"><h3>${phase.title}</h3><p>${phase.subtitle}</p></div><span class="stage-status" data-phase-status="${phase.id}">0 / ${tasks.length}</span></div><p>${phase.exit}</p><div class="owner-links">${plan.roles.filter(role => tasks.some(task => task.role === role.id)).map(role => link(`#role-${role.id}-phase-${phase.id}`, `${role.name} · ${tasks.filter(task => task.role === role.id).length} görev`, 'owner-link')).join('')}</div></li>`;
  }).join('');
  const roles = plan.roles.map(role => `<section class="role-section" id="role-${role.id}" aria-labelledby="heading-${role.id}"><div class="role-heading"><h3 id="heading-${role.id}">${escapeHTML(role.name)}</h3><span class="role-summary" data-role-status="${role.id}">0 / ${core.filter(task => task.role === role.id).length}</span></div><p>${escapeHTML(role.description)}</p><div class="role-phases">${plan.phases.filter(phase => plan.tasks.some(task => task.role === role.id && task.phase === phase.id)).map(phase => {
    const tasks = plan.tasks.filter(task => task.role === role.id && task.phase === phase.id);
    const count = tasks.filter(task => !task.when).length;
    return `<details class="role-phase" id="role-${role.id}-phase-${phase.id}" data-role-phase="${role.id}:${phase.id}" ${role.id === 'sen' && phase.id === 0 ? 'open' : ''} ${count === 0 ? 'hidden' : ''}><summary>0${phase.id + 1} · ${phase.title}<span data-group-status="${role.id}:${phase.id}">0 / ${count}</span></summary><div class="phase-content"><ul class="task-list">${tasks.map(task => renderTask(task, state, plan)).join('')}</ul></div></details>`;
  }).join('')}</div></section>`).join('');
  const flow = (name, steps) => `<figure class="flow"><figcaption>${name}</figcaption><ol class="flow-list">${steps.map(([heading, label, anchor]) => `<li><span class="flow-step">${link(anchor, heading)}</span><span class="flow-label">${label}</span></li>`).join('')}</ol></figure>`;
  return `<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><meta name="description" content="Atonota: genel ve kişisel yol haritaları, koşullu görevler, CI/CD, DNS ve MCP eylem planı."><meta name="referrer" content="strict-origin-when-cross-origin"><title>Atonota — Eylem planı</title><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css"><script type="module" src="./app.mjs"></script></head>
<body><a class="skip-link" href="#main">İçeriğe geç</a><header class="masthead"><a class="brand" href="#main">atonota <span> / eylem planı</span></a><div class="masthead-meta">${plan.date} · <a href="https://github.com/karacaismail/atonota-action-plan" target="_blank" rel="noopener noreferrer">Public repo</a></div></header>
<div class="layout"><nav class="rail" aria-label="Plan bölümleri"><details class="rail-menu" id="rail-menu"><summary>Plan ve kişiler</summary><p>Yol haritası</p><div class="rail-links">${[['#simdi','Şimdi başla'],['#genel','Genel yol'],['#akislar','İş akışları'],['#kisiler','Kişiler'],['#projeler','Projeler'],['#kararlar','Eksikler ve kararlar']].map(([href,label]) => link(href,label,'rail-link')).join('')}</div><p>Kişisel yollar</p><div class="rail-links">${plan.roles.map(role => link(`#role-${role.id}`,role.name,'rail-link')).join('')}</div></details></nav>
<main id="main" tabindex="-1"><div class="hero"><p class="eyebrow">Workbench · MCP · Pen</p><h1>Kurulumdan<br>ilk yayına.</h1><p class="lede">Hazır işe başla. Görev sahibine git.<br>Çıktıyı doğrula, sonraki adımı aç.</p>${link('#simdi','Hazır işlere git','owner-link')}<div class="notice"><strong>Yerel plan takibi.</strong> İşaretler yalnız bu tarayıcıda saklanır; sunucuda işlem, gerçek onay veya deploy sayılmaz.</div><div class="summary" aria-label="Plan özeti"><div class="metric"><strong data-metric="done">0 / ${core.length}</strong><span>tamamlandı · yerel takip</span></div><div class="metric"><strong data-metric="ready">${readyCount}</strong><span>başlanabilir görev</span></div><div class="metric"><strong>6</strong><span>ilişkili aşama</span></div><div class="metric"><strong>4</strong><span>görev sahibi</span></div></div></div>
<section id="simdi">${title('01 / Sıradaki iş', 'Şimdi ne yapacağım?', 'Görev sahibini seç; ön koşulu tamamlanan işe git.')}<div class="toolbar" aria-label="Hazır işleri görev sahibine göre göster"><button type="button" data-owner-filter="all" aria-pressed="true">Herkes</button>${plan.roles.map(role=>`<button type="button" data-owner-filter="${role.id}" aria-pressed="false">${escapeHTML(role.name)}</button>`).join('')}</div><div id="next-actions">${renderNext(plan,state)}</div></section>
<section id="genel">${title('02 / Genel yol', 'Bir aşamadan kişiye geç.', 'Kişi etiketine dokun: kendi yol haritasındaki ilgili aşama açılır. Aşamalar takvim değil, görev bağımlılıklarıdır; bağımsız işler paralel ilerler.')}<ol class="stage-list">${roadmap}</ol><div class="section-heading"><h3>Koşullu iş kolları</h3><p>Yalnız ihtiyacın olan kolu aç. Seçim görevleri gösterir; erişim veya yayın yetkisi vermez.</p></div><div class="branch-options">${plan.options.map(option=>`<div class="option"><label><input type="checkbox" data-option="${option.id}" disabled><span>${option.title}</span></label><small>${option.note}</small></div>`).join('')}</div></section>
<section id="akislar">${title('03 / Devir ve yayın', 'İş akışlarını izle.')} ${flow('DNS: hazırla → uygula → doğrula', [['Föyü hazırla','Hüseyin Cengiz','#task-H04'],['DNS’i uygula','Asistan Hüseyin','#task-A02'],['DNS / TLS kontrolü','Hüseyin Cengiz','#task-H05']])}${flow('Girdi: telefondan sonuç URL’sine', [['Talimat ver','Sen · Claude iOS','#task-U06'],['Yetkiyi doğrula','HTTPS / OAuth MCP','#task-E05'],['İşi kaydet','Kalıcı iş kimliği','#task-E06'],['Oturumda çalıştır','Worker + adaptör','#task-H07'],['Sonucu al','Doğru URL türü','#task-E07']])}${flow('Component: aynı artefaktla kontrollü yayın', [['Kaynak + story','Component manifesti','#task-E04'],['Beta’da test et','CI + Storybook','#task-E10'],['Terfiyi kabul et','Sen','#task-U07'],['RC’ye taşı','Hüseyin Cengiz','#task-H08'],['MCP ile eşitle','Kalıcı yayın işi','#task-E09'],['Pen’de doğrula','Sürüm + checksum','#task-E11']])}</section>
<section id="kisiler">${title('04 / Kişisel yollar', 'Kendi görevlerini tamamla.', 'Ön koşul bağlantısından işi bekleten kişiye geç. Kabul kontrolünü tamamladıktan sonra işaretle.')}<noscript><p class="notice">Planı okuyabilir ve bağlantıları kullanabilirsin. Yerel işaretleme ve koşullu kollar için JavaScript’i etkinleştir.</p></noscript>${roles}</section>
<section id="projeler">${title('05 / Adres ve repo', 'Projeleri ayrı teslim et.', 'Aşağıdaki ürün repo adları öneridir. Mevcut kaynakları ve açık kaynak lisansını onayla; şirket/girişim sahipliğini envanterde tut.')}<div class="project-list">${plan.projects.map(project=>`<article class="project"><div><h3 class="project-name">${project.name}</h3><p class="project-address">${escapeHTML(project.address)}</p></div><div><p>${escapeHTML(project.action)}</p><p class="project-note">Repo: ${escapeHTML(project.repo)}</p>${link(`#task-${project.task}`,`${plan.roles.find(role=>role.id===project.owner).name} · ${project.task}`,'owner-link')}</div></article>`).join('')}</div><p class="notice">/od, /pp ve /b3d birer alt yoldur: DNS kaydı açma. Proxy ve uygulama base path’ini Hüseyin Cengiz doğrulasın. Çalışmazsa yeni adresi önce onayla.</p></section>
<section id="kararlar">${title('06 / Açık işler', 'Eksikleri karar ve testle kapat.')}<ul class="next-actions"><li class="next-item"><h3>Sen: eksik kararları tamamla.</h3><p>Şirket/girişim listesi, domain sahipliği, lisans, erişim sınırları, ilk iş/çıktı türü, model bütçesi ve Affinity yöntemi.</p>${link('#role-sen-phase-0','Karar aşamana git','owner-link')}</li><li class="next-item"><h3>Hüseyin Cengiz: uyumluluk ve işletimi kanıtla.</h3><p>Sunucu kapasitesi, alt yollar, özel ağ sınırları, aktif oturum, yedek/restore ve rollback.</p>${link('#role-cengiz-phase-2','Kurulum aşamasına git','owner-link')}</li><li class="next-item"><h3>Geliştirme ekibi: eksik köprüleri geliştir.</h3><p>OAuth/MCP araçları, kalıcı işler, Open Design/Penpot adaptörleri, Storybook manifesti ve RC → Pen köprüsü.</p>${link('#role-ekip-phase-3','Entegrasyon aşamasına git','owner-link')}</li><li class="next-item"><h3>Yeni riskleri denemelerle yakala.</h3><p>Yanlış proje, iki kez gelen olay, izin iptali, worker restart, model kotası, disk dolması ve kısmi yayın için kabul kanıtı kaydet.</p>${link('#role-cengiz-phase-5','Arıza provasına git','owner-link')}</li></ul></section>
<footer class="footer"><div class="toolbar"><button type="button" id="export-progress" disabled>İlerlemeyi indir</button><button type="button" id="reset-progress" disabled>Yerel işaretleri sıfırla</button></div><p class="completion-feedback" id="feedback" role="status" aria-live="polite">İşaretlemek, gerçek kurulumun tamamlandığı anlamına gelmez.</p><p id="storage-note">Takip verisi bu tarayıcıya özeldir. Senkronize ekip panosu değildir.</p><p>Kaynak kontrolleri: <a href="https://docs.github.com/en/actions/reference/security/secure-use">CI güvenliği</a> · <a href="https://help.penpot.app/mcp/">Penpot MCP</a> · <a href="https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp">Uzak connector</a> · <a href="https://storybook.js.org/docs/sharing/publish-storybook">Storybook yayını</a></p></footer>
</main></div></body></html>`;
}
