import { normalizeState, statusOf, isActive } from '../model.mjs';
import { escapeHTML, statusLabels, renderTask, renderNext, renderDependencyLinks } from '../render.mjs';

const link = (href, label, className = '') => `<a class="${className}" href="${escapeHTML(href)}">${escapeHTML(label)}</a>`;
const title = (number, heading, description = '') => {
  const [index, label] = number.split(' / ');
  return `<div class="section-heading"><p class="eyebrow"><span class="section-number">${escapeHTML(index)}</span><span class="section-label">${escapeHTML(label)}</span></p><h2>${escapeHTML(heading)}</h2>${description ? `<p>${escapeHTML(description)}</p>` : ''}</div>`;
};

export function renderPage(plan, progress = null) {
  const state = normalizeState(progress, plan);
  const roleName = id => plan.roles.find(role => role.id === id).name;
  const active = plan.tasks.filter(task => isActive(task, state));
  const readyCount = active.filter(task => statusOf(task, state, plan) === 'ready').length;
  const personDocs = { sen: 'ismail-karaca', cengiz: 'huseyin-cengiz', asistan: 'asistan-huseyin' };
  const personNotes = { sen: ['İK', 'Repo, kod ve ürün kabulü'], cengiz: ['HC', 'Sunucu, CI/CD ve güvenlik'], asistan: ['AH', 'GoDaddy, domain ve DNS'] };
  const shortcuts = `<section class="role-shortcuts" aria-labelledby="shortcut-heading"><h2 id="shortcut-heading">Kendi yolunu aç</h2><div class="shortcut-list">${plan.roles.map(role => `<a class="role-shortcut" href="#role-${role.id}"><span class="shortcut-index" aria-hidden="true">${personNotes[role.id][0]}</span><span class="shortcut-copy"><strong>${escapeHTML(role.name)}</strong><small class="shortcut-note">${personNotes[role.id][1]}</small></span><span class="shortcut-arrow" aria-hidden="true">↗</span></a>`).join('')}</div></section>`;
  const hero = `<div class="hero"><div class="hero-main"><p class="eyebrow">DevOps ve CI/CD · PoC hazırlığı</p><h1>${escapeHTML(plan.scope?.title ?? 'Altyapıyı hazırla. Siteleri sonra yayınla.')}</h1><p class="lede">${escapeHTML(plan.scope?.summary ?? 'Public repoları, kurulum paketlerini, güvenli erişimi ve otomatik yayın hattını hazırla. Şimdilik çalışan bir index yeterli.')}</p><div class="overview-actions">${link('#simdi','Sıradaki işe geç','overview-action')}<a class="overview-action" href="https://karacaismail.github.io/atonota-workbench/" target="_blank" rel="noopener noreferrer">Workbench’i aç<span class="sr-only"> — yeni sekme</span></a></div></div>${shortcuts}<div class="summary" aria-label="Plan özeti"><div class="metric"><strong data-metric="done">${state.completed.length} / ${active.length}</strong><span>yerel işaret</span></div><div class="metric"><strong data-metric="ready">${readyCount}</strong><span>başlanabilir iş</span></div><div class="metric"><strong>${plan.phases.length}</strong><span>aşama</span></div><div class="metric"><strong>${plan.roles.length}</strong><span>görev sahibi</span></div></div><div class="progress-strip"><label for="plan-progress">Yerel ilerleme <span data-progress-label>${state.completed.length} / ${active.length}</span></label><progress id="plan-progress" value="${state.completed.length}" max="${Math.max(1, active.length)}">${state.completed.length} / ${active.length}</progress></div><div class="hero-support"><details class="known-decisions"><summary>Kapsam ve kayıtlı kararlar</summary><p class="scope-later">${escapeHTML(plan.scope?.later ?? 'Holding sitesini İsmail Karaca daha sonra geliştirecek; CI/CD şimdi hazır olacak.')}</p><ul>${(plan.knownDecisions ?? []).map(decision => `<li><strong>${escapeHTML(decision.label)}:</strong> ${escapeHTML(decision.text)}</li>`).join('')}</ul></details></div><p class="notice"><strong>Yalnız yerel takip.</strong> İşaretler bu tarayıcıda saklanır; sunucuda kurulum veya gerçek onay yapmaz.</p></div>`;
  const roadmap = plan.phases.map(phase => {
    const tasks = active.filter(task => task.phase === phase.id);
    const completed = tasks.filter(task => state.completed.includes(task.id)).length;
    return `<li class="stage" data-phase="${phase.id}"><div class="stage-head"><span class="stage-number">0${phase.id + 1}</span><div class="stage-title"><h3>${escapeHTML(phase.title)}</h3><p>${escapeHTML(phase.subtitle)}</p></div><span class="stage-status" data-phase-status="${phase.id}">${completed} / ${tasks.length}</span></div><p>${escapeHTML(phase.exit)}</p><div class="owner-links">${plan.roles.filter(role => tasks.some(task => task.role === role.id)).map(role => link(`#role-${role.id}-phase-${phase.id}`, `${role.name} · ${tasks.filter(task => task.role === role.id).length} görev`, 'owner-link')).join('')}</div></li>`;
  }).join('');
  const roles = plan.roles.map(role => `<section class="role-section" id="role-${role.id}" aria-labelledby="heading-${role.id}"><div class="role-heading"><h3 id="heading-${role.id}">${escapeHTML(role.name)}</h3><span class="role-summary" data-role-status="${role.id}">${active.filter(task => task.role === role.id && state.completed.includes(task.id)).length} / ${active.filter(task => task.role === role.id).length}</span></div><p>${escapeHTML(role.description)}</p><div class="role-download"><a class="owner-link" href="./docs/${personDocs[role.id]}.md" download="${personDocs[role.id]}.md">${escapeHTML(role.name)} görev dosyasını indir (MD)</a></div><div class="role-phases">${plan.phases.filter(phase => plan.tasks.some(task => task.role === role.id && task.phase === phase.id)).map(phase => {
    const tasks = plan.tasks.filter(task => task.role === role.id && task.phase === phase.id);
    const visible = tasks.filter(task => isActive(task, state));
    return `<details class="role-phase" id="role-${role.id}-phase-${phase.id}" data-role-phase="${role.id}:${phase.id}" ${role.id === 'sen' && phase.id === 0 ? 'open' : ''} ${visible.length === 0 ? 'hidden' : ''}><summary><span class="phase-summary-title"><span class="phase-summary-number">0${phase.id + 1}</span>${escapeHTML(phase.title)}</span><span data-group-status="${role.id}:${phase.id}">${visible.filter(task => state.completed.includes(task.id)).length} / ${visible.length}</span></summary><div class="phase-content"><ul class="task-list">${tasks.map(task => renderTask(task, state, plan)).join('')}</ul></div></details>`;
  }).join('')}</div></section>`).join('');
  const flow = (name, steps, dependencyMap = false) => `<figure class="flow"><figcaption>${escapeHTML(name)}</figcaption><ol class="flow-list${dependencyMap ? ' dependency-map' : ''}">${steps.map(([id, heading, note]) => {
    const task = plan.tasks.find(task => task.id === id);
    const status = statusOf(task, state, plan);
    return `<li data-flow-task="${id}" data-status="${status}"><span class="flow-task-id">${id}</span><span class="flow-step">${link(`#task-${id}`, heading)}</span><span class="flow-label">${link(`#role-${task.role}-phase-${task.phase}`, note ?? roleName(task.role), 'flow-owner-link')}</span><span class="flow-node-state" data-flow-status="${id}">${statusLabels[status]}</span>${dependencyMap ? `<div class="flow-dependencies" data-flow-dependencies="${id}">${renderDependencyLinks(task, state, plan)}</div>` : ''}</li>`;
  }).join('')}</ol></figure>`;
  const branches = `<div class="branch-diagram" aria-label="Seçilen ek iş kolları">${plan.options.map(option => `<section class="branch-node" data-branch="${option.id}" aria-labelledby="branch-heading-${option.id}" ${state.options[option.id] ? '' : 'hidden'}><h3 id="branch-heading-${option.id}">${escapeHTML(option.title)}</h3>${flow('İş kolu düğümleri; ön koşul bağlantılarını izle.', plan.tasks.filter(task => task.when === option.id).sort((left, right) => left.phase - right.phase).map(task => [task.id, task.title]), true)}</section>`).join('')}</div>`;
  return `<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><meta name="description" content="Atonota: genel ve kişisel yol haritaları, koşullu görevler, CI/CD, DNS ve MCP eylem planı."><meta name="referrer" content="strict-origin-when-cross-origin"><title>Atonota — Eylem planı</title><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css"><script type="module" src="./app.mjs"></script></head>
<body><a class="skip-link" href="#main">İçeriğe geç</a><header class="masthead"><a class="brand" href="#main">atonota <span> / eylem planı</span></a><div class="masthead-meta">${escapeHTML(plan.date)} · <a href="https://github.com/karacaismail/atonota-action-plan" target="_blank" rel="noopener noreferrer">Public repo</a></div></header>
<div class="layout"><nav class="rail" aria-label="Plan bölümleri"><details class="rail-menu" id="rail-menu"><summary>Plan ve kişiler</summary><p>Yol haritası</p><div class="rail-links">${[['#simdi','Şimdi başla'],['#genel','Genel yol'],['#akislar','İş akışları'],['#kisiler','Kişiler'],['#projeler','Projeler'],['#kararlar','Eksikler ve kararlar']].map(([href,label]) => link(href,label,'rail-link')).join('')}</div><p>Kişisel yollar</p><div class="rail-links">${plan.roles.map(role => link(`#role-${role.id}`,role.name,'rail-link')).join('')}</div></details></nav>
<main id="main">${hero}
<section id="simdi">${title('01 / Sıradaki iş', 'Şimdi ne yapacağım?', 'İsmini seç, açık işe git. Her görevde ne yapacağın ve kime ne teslim edeceğin yazıyor.')}<div class="toolbar" aria-label="Hazır işleri görev sahibine göre göster"><button type="button" data-owner-filter="all" aria-pressed="true">Herkes</button>${plan.roles.map(role=>`<button type="button" data-owner-filter="${role.id}" aria-pressed="false">${escapeHTML(role.name)}</button>`).join('')}</div><div id="next-actions">${renderNext(plan,state)}</div></section>
<section id="genel">${title('02 / Teknik yol', 'Aşamadan görev sahibine geç.', 'Kişiye dokun: ilgili aşaması açılır. Bağımsız işler paralel ilerler; sayılar yerel işaretlerini gösterir.')}<ol class="stage-list">${roadmap}</ol><div class="section-heading"><h3>Ek iş kolunu aç</h3><p>Seçilen kolun şeması ve görevleri görünür. Seçim gerçek erişim veya yayın izni değildir.</p></div><div class="branch-options">${plan.options.map(option=>`<div class="option"><label><input type="checkbox" data-option="${option.id}" disabled ${state.options[option.id] ? 'checked' : ''}><span>${escapeHTML(option.title)}</span></label><small>${escapeHTML(option.note)}</small></div>`).join('')}</div>${branches}</section>
<section id="akislar">${title('03 / İş akışları', 'Kimden kime, hangi sırayla?', 'Şemalar genel iş sırasını gösterir; gerçek ön koşullar görevde yazılıdır. Üst bağlantı göreve, kişi bağlantısı ilgili aşamasına gider. Durumlar yerel takiptir; servis kanıtı değildir.')}${flow('Repo ve PoC → paket → CI/CD → Hetzner', [['E01','Public repoları hazırla'],['E02','PoC teslimini hazırla'],['E13','Kurulumu Colima’da dene'],['H02','CI/CD’yi bağla'],['H05','Sunucuda doğrula']])}${flow('DNS: Cengiz hazırlar → Asistan uygular → Cengiz doğrular', [['H04','Kayıt listesini ver'],['A02','GoDaddy’de uygula'],['H05','DNS ve TLS’yi doğrula']])}${flow('MCP: telefon → Linux / uygulama → sonuç URL’si', [['E05','MCP ve Linux araçları'],['E06','İşi kalıcı yürüt'],['H07','İzinli servise bağla'],['U06','Claude iOS’u bağla',`${roleName('sen')} · Claude iOS`],['E07','Sonuç URL’sini al']])}${flow('Bileşen: sözleşme → köprü → Beta → RC → Pen', [['E04','Sürüm bilgisini hazırla'],['E09','Yayın köprüsünü kur'],['E10','Beta’da test et'],['U07','Sonucu kabul et'],['H08','Aynı sürümü RC’ye taşı'],['E11','Pen yayınına bak']])}</section>
<section id="kisiler">${title('04 / Kişisel yollar', 'Kendi görevlerini tamamla.', 'İsmail Karaca’nın karar, geliştirme ve kabul görevleri tek yol haritasında. Codex ve Claude Code geliştirme araçlarıdır. Ön koşul bağlantısından ilgili işe geç.')}<noscript><p class="notice">Planı okuyabilir ve bağlantıları kullanabilirsin. Yerel işaretleme ve koşullu kollar için JavaScript’i etkinleştir.</p></noscript>${roles}</section>
<section id="projeler">${title('05 / Uygulamalar', 'Ne hazır, ne kurulacak?', 'Durumlar kullanıcı beyanı veya mevcut kaynak kaydıdır; bu sayfa canlı sunucu kontrolü yapmaz. Workbench yalnız uygulamalara yönlendiren menüdür.')}<div class="project-list">${plan.projects.map(project=>`<article class="project"><div><h3 class="project-name">${escapeHTML(project.name)}</h3><p class="project-address">${escapeHTML(project.address)}</p><p class="project-status"><span>Durum</span> ${escapeHTML(project.status ?? 'Kurulum kabulü bekliyor')}</p></div><div><p>${escapeHTML(project.action)}</p><p class="project-note">Repo: ${escapeHTML(project.repo)}</p>${link(`#task-${project.task}`,`${plan.roles.find(role=>role.id===project.owner).name} görevine git · ${project.task}`,'owner-link')}</div></article>`).join('')}</div><p class="notice">/od, /pp, /ad, /b3d, /sbbeta ve /sbrc DNS kaydı değil, uygulama yoludur. Cengiz proxy, giriş, dosyalar ve WebSocket erişimini birlikte deneyecek.</p></section>
<section id="kararlar">${title('06 / Kalan işler', 'Verilmiş kararları tekrar sorma.', 'Adresler, kişiler, public repo tercihi ve erişim kuralı belli. Şimdi hazırlanacak ve kanıtlanacak işler var.')}<ul class="next-actions"><li class="next-item"><h3>${escapeHTML(roleName('sen'))}: kurulum paketini teslim et.</h3><p>Codex ve Claude Code ile PoC index, public repo, Colima’da denenmiş kurulum komutu ve CI dosyalarını hazırla. Holding’in gerçek içeriği daha sonra.</p>${link('#task-E13','Paket teslim görevine git','owner-link')}</li><li class="next-item"><h3>${escapeHTML(roleName('cengiz'))}: kurulumu ve güvenliği doğrula.</h3><p>Penpot ve Affinity’yi kur. Blender’daki mevcut çalışmanın sonucunu al; yeniden kurulum varsayma. Web arayüzünü girişle koru; web yoksa uygun ücretsiz Tailscale erişimini dene.</p>${link('#role-cengiz-phase-2','Kurulum aşamasına git','owner-link')}</li><li class="next-item"><h3>${escapeHTML(roleName('asistan'))}: verilen DNS listesini uygula.</h3><p>Hüseyin Cengiz’den kayıt türünü, adını ve değerini al. GoDaddy’de uygula, sonucu Hüseyin Cengiz’e ilet.</p>${link('#task-A02','DNS görevine git','owner-link')}</li><li class="next-item"><h3>${escapeHTML(roleName('sen'))}: Linux ve uygulamalar için MCP’yi geliştir.</h3><p>Telefondan Claude veya girişli form ile komut ver; izinli sunucu işi devam etsin, durumu ve sonuç URL’si dönsün. Bu bağlantı henüz kurulmuş değil.</p>${link('#task-E05','MCP geliştirme görevine git','owner-link')}</li></ul><p class="notice">Yeni özgün kodun lisansı ayrı karar bekliyor. ${link('#task-U02','Lisans görevini gör')}. Şirket adları ve site içeriği PoC/CI-CD hazırlığını bekletmez.</p></section>
<footer class="footer"><a class="owner-link" href="./docs/genel-yol.md" download="genel-yol.md">Genel eylem kılavuzunu indir (MD)</a><div class="toolbar"><button type="button" id="export-progress" disabled>İlerlemeyi indir</button><button type="button" id="reset-progress" disabled>Yerel işaretleri sıfırla</button></div><p class="completion-feedback" id="feedback" role="status" aria-live="polite">İşaretlemek, gerçek kurulumun tamamlandığı anlamına gelmez.</p><p id="storage-note">Takip verisi bu tarayıcıya özeldir. Senkronize ekip panosu değildir.</p><details class="source-notes"><summary>Teknik kaynaklar</summary><div><a href="https://docs.github.com/en/actions/reference/security/secure-use">CI güvenliği</a><a href="https://help.penpot.app/mcp/">Penpot MCP</a><a href="https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp">Claude uzak MCP</a><a href="https://storybook.js.org/docs/sharing/publish-storybook">Storybook yayını</a><a href="https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html">Nginx giriş koruması</a><a href="https://tailscale.com/docs/account/manage-plans/free-plans-discounts">Tailscale ücretsiz erişim</a><a href="https://www.affinity.studio/get-affinity">Affinity platformları</a><a href="https://developers.google.com/search/docs/crawling-indexing/block-indexing">Google noindex</a></div></details></footer>
</main></div></body></html>`;
}
